/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        // Material Design 3 tokens (from Stitch brutalist design)
        "tertiary-fixed": "#ffdf93",
        "surface-container-high": "#ece6ee",
        "on-tertiary-fixed-variant": "#594400",
        "tertiary-container": "#c9a74d",
        "surface-bright": "#fdf7ff",
        "surface-variant": "#e6e0e9",
        "tertiary-fixed-dim": "#e7c365",
        "on-secondary": "#ffffff",
        "primary-fixed-dim": "#cfbcff",
        "surface-container": "#f2ecf4",
        "on-error": "#ffffff",
        primary: "#4f378a",
        "on-background": "#1d1b20",
        "error-container": "#ffdad6",
        "on-primary-fixed-variant": "#4f378a",
        "secondary-fixed-dim": "#cdc0e9",
        error: "#ba1a1a",
        tertiary: "#765b00",
        "primary-fixed": "#e9ddff",
        "surface-container-low": "#f8f2fa",
        "on-primary": "#ffffff",
        "on-tertiary": "#ffffff",
        "surface-tint": "#6750a4",
        "on-surface-variant": "#494551",
        "secondary-fixed": "#e9ddff",
        "on-secondary-fixed": "#1f1635",
        "on-secondary-fixed-variant": "#4b4263",
        "inverse-surface": "#322f35",
        "on-primary-container": "#e0d2ff",
        outline: "#7a7582",
        surface: "#fdf7ff",
        "primary-container": "#6750a4",
        "secondary-container": "#e1d4fd",
        "surface-container-highest": "#e6e0e9",
        "on-tertiary-fixed": "#241a00",
        secondary: "#63597c",
        "on-primary-fixed": "#22005d",
        "on-surface": "#1d1b20",
        "inverse-primary": "#cfbcff",
        "on-error-container": "#93000a",
        "inverse-on-surface": "#f5eff7",
        "surface-dim": "#ded8e0",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-container": "#503d00",
        "outline-variant": "#cbc4d2",
        "on-secondary-container": "#645a7d",
        background: "#fdf7ff",
        // Accent
        ink: "#2A2A2A",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      fontFamily: {
        headline: ["Public Sans", "sans-serif"],
        display: ["Public Sans", "sans-serif"],
        body: ["Public Sans", "sans-serif"],
        label: ["Public Sans", "sans-serif"],
        serif: ["DM Serif Display", "serif"],
        mono: ["IBM Plex Mono", "monospace"],
        grotesk: ["Space Grotesk", "sans-serif"],
      },
      boxShadow: {
        brutal: "4px 4px 0px 0px #2A2A2A",
        "brutal-sm": "2px 2px 0px 0px #2A2A2A",
        "brutal-lg": "6px 6px 0px 0px #2A2A2A",
        "brutal-primary": "4px 4px 0px 0px #4f378a",
      },
      animation: {
        "fade-in": "fadeIn 0.3s ease-in-out",
        "slide-up": "slideUp 0.4s ease-out",
        "pulse-slow": "pulse 3s infinite",
      },
      keyframes: {
        fadeIn: {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        slideUp: {
          "0%": { opacity: "0", transform: "translateY(20px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
      },
    },
  },
  plugins: [],
};
