"""profile and exit survey

Revision ID: 86373c9fe5af
Revises: 
Create Date: 2026-07-04 16:06:09.539779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86373c9fe5af'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('college_start_year', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('college_end_year', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('course', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('skills', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('skills')
        batch_op.drop_column('course')
        batch_op.drop_column('college_end_year')
        batch_op.drop_column('college_start_year')

    # ### end Alembic commands ###
