"""add show_ai_analysis

Revision ID: b75eff003a3a
Revises: 86373c9fe5af
Create Date: 2026-07-04 17:04:48.603248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b75eff003a3a'
down_revision = '86373c9fe5af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('show_ai_analysis', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('show_ai_analysis')

    # ### end Alembic commands ###
